package blessing-skin:plugin@1.0.0;

interface host {
    log: func(level: string, message: string) -> result<_, string>;
}

interface state {
    get: func(key: string) -> result<option<list<u8>>, string>;
    set: func(key: string, value: list<u8>) -> result<_, string>;
    delete: func(key: string) -> result<bool, string>;
}

interface lifecycle {
    initialize: func(host-api-version: string) -> result<_, string>;
    shutdown: func();
}

interface events {
    handle: func(name: string, payload: list<u8>) -> result<_, string>;
}

interface filters {
    apply: func(name: string, value: string, context: string) -> result<option<string>, string>;
}

interface documentation {
    readme: func() -> result<option<string>, string>;
}

interface configuration {
    get: func() -> result<option<string>, string>;
    set: func(configuration: string) -> result<_, string>;
}

world plugin {
    import host;
    import state;
    export lifecycle;
    export events;
    export filters;
    export documentation;
    export configuration;
}
